### ISSUE TITLE
setup.py installs latest version of cvxpy, but primitive annotation lists 0.4.11

### ISSUE THREAD

**Issue by mitar** [dvdmjohnson/d3m_michigan_primitives#1]
Which one you want?

Also, why do you even have to manually install cvxpy inside setup.py?

**Comment by mitar** [comment]
So the problem is that this broke image building for v2019.4.4 because you do not have an upper version defined on `cvxpy`, so it always installs the latest version. But latest version of `cvxpy` is broken: https://github.com/cvxgrp/cvxpy/issues/727

It took me 2 days to figure what is happening here. :-(

**Comment by mitar** [comment]
At the end I had to disable primitive annotations because of this. It was breaking validation.

**Comment by mitar** [comment]
Please bump your dependency to `1.0.23`. They fixes this issue upstream.

**Comment by dvdmjohnson** [comment]
Fixed in local update.
