### ISSUE TITLE
GRASTAAutoPricePipeline gets bad score

### ISSUE THREAD

**Issue by rszeto** [dvdmjohnson/d3m_michigan_primitives#18]
Baseline: 6985720
Best: 3062810
Current: 7197392

**Comment by rszeto** [comment]
Current score on choroid is 32024384.517778624 **(VERY DIFFERENT)**

**Comment by rszeto** [comment]
Current score is about 7197392 on both machines now.

**Comment by kgilman** [comment]
To do: tweak hyperparameters...record any improvements or worse results.

**Comment by rszeto** [comment]
Won't be addressed until after #38

**Comment by rszeto** [comment]
Now depends on #41
