### ISSUE TITLE
Replace our VGG primitive with ISI's for hand geometry pipelines

### ISSUE THREAD

**Issue by rszeto** [dvdmjohnson/d3m_michigan_primitives#33]
Our VGG primitive is broken due to an upgrade to TensorFlow 2.0; this has broken all of our hand geometry pipelines due to their dependence on it. However, ISI has been maintaining their own VGG primitive. Let's try replacing our VGG primitive with theirs in our pipelines.

[Info on ISI VGG primitive](https://marvin-beta.datadrivendiscovery.org/primitives?Search=%22DSBox+Image+Featurizer+VGG16%22)

Pipelines to be modified:
- [ ] PCPIALMHandgeometryPipeline
- [ ] RPCALBDHandgeometryPipeline

**Comment by zeonzir** [comment]
Was able to install the dsbox featurization code. However, when trying to run their internal unit tests they failed. Apart from coding issues (possibly from varying d3m versions), their code internally uses something called d3mIndex which I haven't encountered before. There are ALOT of bugs in the pipeline w.r.t. shapes of tensors. I have reached out to the author kyao@isi.edu regarding this.

**Comment by rszeto** [comment]
These files might be useful for downloading volumes, i.e., model weights:

https://gitlab.com/datadrivendiscovery/d3m/-/blob/devel/d3m/index.py
https://gitlab.com/datadrivendiscovery/d3m/-/blob/devel/d3m/cli.py

Seems like you should be able to download by running `python3 -m d3m index download`. However, nothing actually happens.

**Comment by rszeto** [comment]
We might be in luck with the volume. The hash [here](https://github.com/usc-isi-i2/dsbox-featurizer/blob/master/dsbox/datapreprocessing/featurizer/image/net_image_feature.py#L153) is already in our volumes folder.
