### ISSUE TITLE
GRASTA Tracking Issue

### ISSUE THREAD

**Issue by kgilman** [dvdmjohnson/d3m_michigan_primitives#41]
GRASTA lags in tracking (substantially). This is a bug with the step size choice. Determine whether this bug has been present through all versions or was introduced in most recent commit.

**Comment by rszeto** [comment]
@zeonzir Help Kyle figure out whether the bug exists in the following two commits:

* e2b36ea1115b4bfd6e5b84a14635ba3dca8e4971 (the most recent master commit)
* e3644f34481bc3e4c7c1de3d84ab780cde57d3ac (the commit before Kyle's interface changes)

**Comment by rszeto** [comment]
From today's meeting, sounds like we had misdiagnosed the tracking behavior, and the Python GRASTA implementation might be behaving correctly. @kgilman will compare the behavior with the original authors' MATLAB code to confirm.

**Comment by kgilman** [comment]
Tracking behavior between the Python GRASTA primitive and the author's MATLAB code is consistent.
